controllers:
    resource: ../src/Controller/
    type: attribute
route_accueil:
    path: /accueil
    controller: App\Controller\EleveController::index
eleveAjouter:
    path: /eleve/ajouter
    controller: App\Controller\EleveController::ajouter
eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve
etudiantLister:
    path: /eleve/lister/{id}
    controller: App\Controller\EleveController::listerEleve
responsableAjouter:
    path: /responsable/ajouter
    controller: App\Controller\ResponsableController::ajouter
responsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable
responsableLister:
    path: /responsable/lister/{id}
    controller: App\Controller\ResponsableController::listerResponsable
inscriptionAjouter:
    path: /inscription/ajouter
    controller: App\Controller\InscriptionController::ajouter
inscriptionConsulter:
    path: /inscription/consulter/{id}
    controller: App\Controller\InscriptionController::consulterInscription
inscriptionLister:
    path: /inscription/lister/{id}
    controller: App\Controller\InscriptionController::listerInscription
coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouter
coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consultercours
coursLister:
    path: /cours/lister/{id}
    controller: App\Controller\CoursController::listercours
instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouter
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterinstrument
instrumentLister:
    path: /instrument/lister/{id}
    controller: App\Controller\InstrumentController::listerinstrument
professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouter
professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterprofesseur
professeurLister:
    path: /professeur/lister/{id}
    controller: App\Controller\ProfesseurController::listerprofesseur