controllers:
    resource: ../src/Controller/
    type: attribute
routeIndex:
    path: /accueil
    controller: App\Controller\IndexController::index
routeInscription:
    path: /inscription
    controller: App\Controller\IndexController::inscriptionPage