controllers:
    resource: ../src/Controller/
    type: attribute
routeIndex:
    path: /accueil
    controller: App\Controller\IndexController::index
routeInscription:
    path: /inscription
    controller: App\Controller\IndexController::inscriptionPage
routeAdherentConsultationInformation:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterInformation
instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument 
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument 
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument 
classeInstrumentAjouter:
    path: /classeInstrument/ajouter/
    controller: App\Controller\ClasseInstrumentController::ajouterClasseInstrument
couleurAjouter:
    path: /couleur/ajouter/
    controller: App\Controller\CouleurController::ajouterCouleur 
couleurLister:
    path: /couleur/lister/
    controller: App\Controller\CouleurController::listerCouleur 
marqueAjouter:
    path: /marque/ajouter/
    controller: App\Controller\MarqueController::ajouterMarque 
typeInstrumentAjouter:
    path: /typeInstrument/ajouter/
    controller: App\Controller\TypeIntrumentController::ajouterTypeInstrument 
accessoireAjouter:
    path: /accessoire/ajouter/
    controller: App\Controller\AccessoireController::ajouterAccessoire
accessoireLister:
    path: /accessoire/lister/
    controller: App\Controller\AccessoireController::listerAccessoire