controllers:
    resource: ../src/Controller/
    type: attribute
routeIndex:
    path: /accueil
    controller: App\Controller\IndexController::index
routeInscription:
    path: /inscription
    controller: App\Controller\IndexController::inscriptionPage
routeAdherentConsultationInformation:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterInformation
instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument 
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument 
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument
consulterCours:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours
