controllers:
    resource: ../src/Controller/
    type: attribute
routeInscription:
    path: /inscription
    controller: App\Controller\CompteController::inscriptionPage
instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument
classeInstrumentConsulter:
    path: /classeInstrument/ajouter/
    controller: App\Controller\ClasseInstrumentController::ajouterClasseInstrument
routeAdherentConsultationInformation:
    path: /compte/consulter/{id}
    controller: App\Controller\CompteController::consulterInformation
consulterCours:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours
listerCours:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours
loginPage:
    path: /login
    controller: App\Controller\LoginController::index
accueilPage:
    path: /accueil
    controller: App\Controller\IndexController::accueil
modifierInformationCompte:
    path: /compte/modifier
    controller: App\Controller\CompteController::modifierInformationCompte
app_logout:
    path: /logout
    methods: GET
eleveAjouter:
    path: /eleve/ajouter
    controller: App\Controller\EleveController::ajouter
eleveConsulter:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterEleve
etudiantLister:
    path: /eleve/lister/{id}
    controller: App\Controller\EleveController::listerEleve
responsableAjouter:
    path: /responsable/ajouter
    controller: App\Controller\ResponsableController::ajouter
responsableConsulter:
    path: /responsable/consulter/{id}
    controller: App\Controller\ResponsableController::consulterResponsable
responsableLister:
    path: /responsable/lister/{id}
    controller: App\Controller\ResponsableController::listerResponsable
inscriptionAjouter:
    path: /inscription/ajouter
    controller: App\Controller\InscriptionController::ajouter
inscriptionConsulter:
    path: /inscription/consulter/{id}
    controller: App\Controller\InscriptionController::consulterInscription
inscriptionLister:
    path: /inscription/lister/{id}
    controller: App\Controller\InscriptionController::listerInscription
coursAjouter:
    path: /cours/ajouter
    controller: App\Controller\CoursController::ajouter
coursConsulter:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consultercours
coursLister:
    path: /cours/lister/{id}
    controller: App\Controller\CoursController::listercours
professeurAjouter:
    path: /professeur/ajouter
    controller: App\Controller\ProfesseurController::ajouter
professeurConsulter:
    path: /professeur/consulter/{id}
    controller: App\Controller\ProfesseurController::consulterprofesseur
professeurLister:
    path: /professeur/lister/{id}
    controller: App\Controller\ProfesseurController::listerprofesseur
adminIndexPage:
    path: /admin/index
    controller: App\Controller\AdminController::indexAdmin
adminListerUtilisateurs:
    path: /admin/listerUtilisateurs
    controller: App\Controller\AdminController::listerUtilisateurs
consulterPlanning:
    path: /planning/{id}
    controller: App\Controller\CoursController::monPlanning