controllers:
    resource: ../src/Controller/
    type: attribute
routeIndex:
    path: /accueil
    controller: App\Controller\IndexController::index
routeInscription:
    path: /inscription
    controller: App\Controller\IndexController::inscriptionPage
routeAdherentConsultationInformation:
    path: /eleve/consulter/{id}
    controller: App\Controller\EleveController::consulterInformation
routeInscription:
    path: /inscription
    controller: App\Controller\CompteController::inscriptionPage
instrumentAjouter:
    path: /instrument/ajouter
    controller: App\Controller\InstrumentController::ajouterInstrument 
instrumentConsulter:
    path: /instrument/consulter/{id}
    controller: App\Controller\InstrumentController::consulterInstrument 
instrumentLister:
    path: /instrument/lister
    controller: App\Controller\InstrumentController::listerInstrument 
classeInstrumentConsulter:
    path: /classeInstrument/ajouter/
    controller: App\Controller\ClasseInstrumentController::ajouterClasseInstrument 
routeAdherentConsultationInformation:
    path: /compte/consulter/{id}
    controller: App\Controller\CompteController::consulterInformation
consulterCours:
    path: /cours/consulter/{id}
    controller: App\Controller\CoursController::consulterCours
listerCours:
    path: /cours/lister
    controller: App\Controller\CoursController::listerCours
loginPage:
    path: /accueil
    controller: App\Controller\LoginController::index
modifierInformationCompte:
    path: /compte/modifier
    controller: App\Controller\CompteController::modifierInformationCompte
app_logout:
    path: /logout
    methods: GET
classeInstrumentAjouter:
    path: /classeInstrument/ajouter/
    controller: App\Controller\ClasseInstrumentController::ajouterClasseInstrument
couleurAjouter:
    path: /couleur/ajouter/
    controller: App\Controller\CouleurController::ajouterCouleur 
couleurLister:
    path: /couleur/lister/
    controller: App\Controller\CouleurController::listerCouleur 
marqueAjouter:
    path: /marque/ajouter/
    controller: App\Controller\MarqueController::ajouterMarque 
typeInstrumentAjouter:
    path: /typeInstrument/ajouter/
    controller: App\Controller\TypeIntrumentController::ajouterTypeInstrument 
accessoireAjouter:
    path: /accessoire/ajouter/
    controller: App\Controller\AccessoireController::ajouterAccessoire
accessoireLister:
    path: /accessoire/lister/
    controller: App\Controller\AccessoireController::listerAccessoire