controllers:
    resource: ../src/Controller/
    type: attribute
routeIndex:
    path: /accueil
    controller: App\Controller\IndexController::index
routeInscription:
    path: /inscription
    controller: App\Controller\IndexController::inscriptionPage
routeAdherentConsultationInformation:
    path: /compte/consulter/{id}
    controller: App\Controller\CompteController::consulterInformation
etudiantAjouter:
    path: /etudiant/ajouter
    controller: App\Controller\EtudiantController::ajouter